name: 'Terraform AKS Deployment'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Initialize Terraform'
        run: terraform init

      - name: 'Validate Terraform'
        run: terraform validate

      - name: 'Plan Terraform'
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      # Commented out the Apply step
      # - name: 'Apply Terraform'
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -input=false -auto-approve tfplan
